influxdb:
  image: influxdb:1.7.6
  container_name: influxdb
  ports:
    - '2004:2004'
    - '8083:8083'
    - '8086:8086'
  volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf

chronograf:
    image: chronograf:latest
    volumes:
        - chronograf_data:/var/lib/chronograf
    links:
        - influxdb
    ports:
        - 8087:8888
    restart: always